[tool.black]
line-length = 140
target-version = ["py311"]

[tool.flake8]
max-complexity = 20
max-line-length = 140
extend-ignore = ["E203", "E231", "E501", "W503", "C901"]
extend-exclude = ["dags/**/airflow_db_cleanup.py"]

[tool.isort]
profile = "black"
color_output = false
# skip_gitignore = true
line_length = 140
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true


[tool.mypy]
# Optionals
ignore_missing_imports = true

# Strictness
allow_untyped_globals = false
allow_redefinition = false
implicit_reexport = false
strict_equality = true

# Warnings
warn_unused_ignores = true
warn_no_return = true
warn_return_any = false
warn_redundant_casts = true
warn_unreachable = true

# Error output
show_column_numbers = true
show_error_context = true
show_error_codes = true
show_traceback = true
pretty = true
color_output = true
error_summary = true

[tool.pytest.ini_options]
filterwarnings = ["ignore:::DeprecationWarning"]
